title: Historical Events
description: A collection of historical events for every day in the last 100 years.
baseurl: "" # leave blank for GitHub Pages
url: "https://your-username.github.io" # Replace with your GitHub username
theme: minima
markdown: kramdown
